title: Survive the August
email: info+sta@sglorch.de
description: Survive the August Minecraft Projekt
baseurl: "" 
url: "https://sta.sglorch.de"
github_username:  sglorch
future: true
# Build settings
#theme: minima
#theme: just-the-docs
remote_theme: daattali/beautiful-jekyll@5.0.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
